### ISSUE TITLE
Discuss: API for manipulating the existing contents of a pen?

### ISSUE THREAD

**Issue by papandreou** [sunesimonsen/magicpen#3]
See https://github.com/sunesimonsen/unexpected/pull/66

Right now there's basically only the `removeFormatting` method.

A crazy idea could be a `String.prototype.replace`-ish method (except that it should probably mutate the object in-place). Would be totally cool if you could go:

```javascript
pen.replace(/foo/g, function (subpen) {
    return subpen.clone().text('foobar', 'green');
});
```

I know it'd be expensive because you'd have to serialize the pen to text in order to match it against a regexp, then run `regexp.exec` on it, find `regExp.lastIndex` in the actual pen, then optionally divide some fragments up so they align with the needle etc. Would be really powerful, though :)

Could also be fun to explore the concept of having a movable cursor that'd allow the regular methods to insert text in the middle of an existing chunk instead of only at the end.

**Comment by papandreou** [comment]
Here's a diff where the diff highlighting is not aligned with the tokenization used for the syntax highlighting: https://github.com/sunesimonsen/unexpected/commit/377150907c765dab09b6bc065d987592307f8f0a#diff-0a56a2b979f6080486ec1909508cda1a (line 19).

**Comment by sunesimonsen** [comment]
Sorry, I actually already realized that my suggestion would not work for the cases you highlight, I just forgot to follow up. I still need to understand where we need this functionality, are you doing something new with diffing source code that I don't know about? It might be an idea to allow restyling of ranges, I don't know.

**Comment by papandreou** [comment]
No, I haven't started any work yet, I just realized that we'll need to advance our tech if we want to support syntax highlighted diffs. I don't know what I think the ideal magicpen API would be, and there's also a chance that most of it actually belongs in magicpen-prism unless we want to onboard diffs and tokenization of various languages in magicpen itself.

Just consider it a follow-up to my remark from about half a year ago that I couldn't come up with a use case for cross-chunk replacement. At least it's tangentially related.

**Comment by sunesimonsen** [comment]
Perfectly fine - the reason I ask is because I think supporting this could become pretty complicated, so there must be some real life need ;-)

**Comment by sunesimonsen** [comment]
Restyling a range would fix the API well, so I have nothing again supporting that.

**Comment by papandreou** [comment]
Restyling a range -- interesting. Exactly what do you mean by that?

**Comment by sunesimonsen** [comment]
I could be something along the lines:

```js
pen.replaceTextInRange(42, 84, /.*/g, function (styles, text) {
    styles.push('cyan');
    var args = [text].concat(styles);
    this.text.apply(this, args);
});
```

Overriding styles like this works from v4.1:

```js
pen.text('Should be red', 'blue', 'red');
```

In the case of syntax highlighting we probably want the current styles to take precedence:

```js
pen.replaceTextInRange(42, 84, /.*/g, function (styles, text) {
    styles.unshift('cyan');
    var args = [text].concat(styles);
    this.text.apply(this, args);
});
```

I not sure if that kind of change would be powerful enough to allow overlaying the syntax highlighting on top of the diff.

**Comment by papandreou** [comment]
@sunesimonsen and I had a conversation about this, and we're no longer convinced that there is that much of a use case for this. Initially this appeared to be a nifty way to improve string diffs produced by another library, but we'd rather do modules that build correct magicpen output in the first place.

Let's reopen if new use cases are brought to the table.
